name: domoticz-docker-build

on: 
  schedule:
    - cron: '0 10 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build .
